Repository mongodb/mongoid, pull requests merged in 2021-09, with the labels that each got.

#5029 MONGOID-5029 #empty method should use an #exists? rather than a #count query
  lib/mongoid/association/referenced/has_many/enumerable.rb
  spec/mongoid/association/referenced/has_many/enumerable_spec.rb
  spec/mongoid/association/referenced/has_many/proxy_spec.rb
Labels: oleg-done

#5043 MONGOID-5131: Set up build pipeline for outside contributors
  .evergreen/make-github-actions
  .github/workflows/test.yml
  spec/mongoid/factory_spec.rb
  spec/support/spec_config.rb
Labels: oleg-deferred

#5048 Fix MONGOID-5006 Link default auth source documentation to driver instead of incorrectly claiming "admin" is always the default
  docs/reference/configuration.txt
  docs/reference/queries.txt
  docs/release-notes/mongoid-7.2.txt
Labels: oleg-done

#5076 MONGOID-5103 Implement eq symbol operator
  lib/mongoid/criteria/queryable/selectable.rb
  spec/mongoid/criteria_spec.rb
Labels: oleg-done

#5082 MONGOID-4592 Add examples of using read_attribute and write_attribute to implement custom field behavior
  docs/reference/fields.txt
Labels: oleg-done

#5030 RUBY-2675 test coverage on the Mongoid side
  spec/mongoid/query_cache_spec.rb
Labels: oleg-check

#5047 MONGOID-5151 Respect aliased fields in pluck/distinct by having Document.database_field_name recursively consider embedded docs
  docs/reference/queries.txt
  docs/release-notes/mongoid-7.4.txt
  lib/mongoid/association/macros.rb
  lib/mongoid/fields.rb
  spec/integration/criteria/alias_query_spec.rb
  spec/mongoid/fields_spec.rb
  spec/support/models/country_code.rb
  spec/support/models/passport.rb
  spec/support/models/phone.rb
Labels: oleg-done

#5049 MONGOID-5005 - .sum, .count, and similar aggregables should ignore sort if not limiting/skipping
  docs/release-notes/mongoid-7.4.txt
  lib/mongoid/contextual/aggregable/mongo.rb
  spec/mongoid/contextual/aggregable/mongo_spec.rb
Labels: oleg-done

#5017 MONGOID-5128 Scoped associations
  docs/reference/associations.txt
  docs/reference/queries.txt
  docs/release-notes/mongoid-7.4.txt
  lib/mongoid/association/referenced/belongs_to.rb
  lib/mongoid/association/referenced/belongs_to/buildable.rb
  lib/mongoid/association/referenced/eager.rb
  lib/mongoid/association/referenced/has_and_belongs_to_many.rb
  lib/mongoid/association/referenced/has_many.rb
  lib/mongoid/association/referenced/has_one.rb
  lib/mongoid/association/referenced/has_one/buildable.rb
  lib/mongoid/criteria/scopable.rb
  spec/integration/associations/scope_option_spec.rb
  spec/mongoid/association/referenced/belongs_to/buildable_spec.rb
  spec/mongoid/association/referenced/belongs_to/eager_spec.rb
  spec/mongoid/association/referenced/belongs_to_spec.rb
  spec/mongoid/association/referenced/has_and_belongs_to_many/buildable_spec.rb
  spec/mongoid/association/referenced/has_and_belongs_to_many/eager_spec.rb
  spec/mongoid/association/referenced/has_and_belongs_to_many_models.rb
  spec/mongoid/association/referenced/has_and_belongs_to_many_spec.rb
  spec/mongoid/association/referenced/has_many/buildable_spec.rb
  spec/mongoid/association/referenced/has_many/eager_spec.rb
  spec/mongoid/association/referenced/has_many_models.rb
  spec/mongoid/association/referenced/has_many_spec.rb
  spec/mongoid/association/referenced/has_one/buildable_spec.rb
  spec/mongoid/association/referenced/has_one/eager_spec.rb
  spec/mongoid/association/referenced/has_one_models.rb
  spec/mongoid/association/referenced/has_one_spec.rb
  spec/mongoid/attributes_spec.rb
  spec/mongoid/contextual/atomic_spec.rb
  spec/mongoid/criteria/scopable_spec.rb
  spec/support/models/account.rb
  spec/support/models/artist.rb
  spec/support/models/band.rb
Labels: tracked-in-jira, oleg-done

#5046 MONGOID-5144 Improve query cache docs
  docs/reference/configuration.txt
  docs/reference/queries.txt
Labels: oleg-done

#5036 MONGOID-4755 None criteria class should support #sum, #avg, #min, #max, #aggregates
  lib/mongoid/contextual/aggregable.rb
  lib/mongoid/contextual/aggregable/memory.rb
  lib/mongoid/contextual/aggregable/mongo.rb
  lib/mongoid/contextual/aggregable/none.rb
  lib/mongoid/contextual/none.rb
  spec/mongoid/contextual/aggregable/memory_spec.rb
  spec/mongoid/contextual/aggregable/mongo_spec.rb
  spec/mongoid/contextual/aggregable/none_spec.rb
  spec/mongoid/contextual/none_spec.rb
Labels: oleg-done

#5025 MONGOID-5098 Standardize/improve Range queries -- .where(field: 1..3)
  lib/mongoid/criteria/queryable/extensions/object.rb
  lib/mongoid/criteria/queryable/extensions/range.rb
  spec/integration/criteria/range_spec.rb
  spec/mongoid/criteria/queryable/extensions/range_spec.rb
Labels: oleg-done
